# Generated by Django 3.1.4 on 2020-12-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_article_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='desc',
        ),
    ]
