# Generated by Django 3.1.4 on 2021-01-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
